language: elixir
sudo: false # to use faster container based build environment
elixir:
  - 1.4.4
otp_release:
  - 19.3
matrix:
  include:
    - elixir: 1.4.4
      otp_release: 19.3
    - elixir: 1.4.5
      otp_release: 20.0
script: mix test
after_script:
  - mix deps.get --only dev
  - MIX_ENV=dev mix inch.report
cache:
  directories:
    - _build
    - deps
